---
- name: Install Required Packages | Homebrew
  homebrew_cask: name=cloak state=present
  when: ansible_distribution == 'MacOSX'

- name: Add Cloak to Dock
  shell: dockutil --find 'Cloak' || dockutil --add '~/Applications/Cloak.app'
  changed_when: False
  when: ansible_distribution == 'MacOSX'
