---
- name: Install Required Packages | Homebrew
  homebrew: name=macvim state=latest
  when: ansible_distribution == 'MacOSX'
  register: macvim_install

- name: Link MacVim | Homebrew
  command: brew linkapps macvim
  when: macvim_install.changed

- name: Add MacVim to Dock
  shell: dockutil --add '/Applications/MacVim.app' --label 'MacVim' --replacing 'MacVim'
  changed_when: False
  when: ansible_distribution == 'MacOSX'
