---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      become: true
      changed_when: false

    - name: Install Minimal GSettings Functionality
      package:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - dbus-x11
        - libglib2.0-bin
