---
- name: Install PlEnv
  git: repo={{ plenv_repo_url }} dest={{ plenv_root_directory }}
  tags: plenv-install

- name: Install PlEnv Plugins
  git: repo={{ item.repo }} dest={{ plenv_plugins_directory}}/{{ item.dest }}
  with_items: '{{ plenv_plugins }}'
  tags: plenv-install-plugins

- name: Configure Bash Profile
  template: src=bash.j2 dest={{ bash_profile_directory }}/plenv
  tags: plenv-bash-profile

- name: Configure Bash Completions
  file:
    path: '{{ bash_completion_directory }}/plenv'
    src: '{{ plenv_completions_directory }}/plenv.bash'
    state: link
  tags: plenv-bash-completion

- name: Load Installed Versions
  shell: "{{ plenv_binary }} versions --bare"
  register: plenv_installed_versions
  changed_when: False
  tags: perl-cleanup

- name: Remove Older Versions
  shell: "{{ plenv_binary }} uninstall -f {{ item }}"
  args:
    removes: "{{ perl_versions_directory }}/{{ item }}"
  when: item not in perl_versions
  with_items: "{{ plenv_installed_versions.stdout_lines }}"
  tags: perl-cleanup
  notify: rehash plenv
