---
galaxy_info:
  author: Christopher H. Laco
  description: Install and configure the Solarized themes
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - development
    - system
dependencies:
  - { role: git }
