---
- name: Install Required Packages | Packages
  homebrew_cask: name={{ item }} state=present
  with_items: '{{ google_chrome_required_packages[ansible_distribution | lower] | default([]) }}'
  when: ansible_distribution == 'MacOSX'

- name: Install Required Packages | Packages
  package: name={{ item }} state=latest
  become: yes
  with_items: '{{ google_chrome_required_packages[ansible_distribution | lower] | default([]) }}'
  when: ansible_distribution != 'MacOSX'

- name: Add Google Chrome to Dock
  shell: dockutil --add '/Applications/Google Chrome.app' --label 'Google Chrome' --replacing 'Google Chrome'
  changed_when: False
  when: ansible_distribution == 'MacOSX'
