---
galaxy_info:
  author: Christopher H. Laco
  description: Install and configure System76 drivers
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - all
  categories:
    - system
dependencies: []
