---
- name: Configure Raspberry Pis
  hosts: raspberries
  tags: raspberries
  roles:
    - { role: move_root, tags: move_root }

    #- { role: common, tags: common }
  #tasks:
    #- name: Set Hostname
      #shell: hostnamectl set-hostname {{ inventory_hostname }}
      #sudo: yes
      #tags: hostname

    #- name: Clone Root Mover
      #git:
        #repo: https://github.com/adafruit/Adafruit-Pi-ExternalRoot-Helper.git
        #dest: ~/Adafruit-Pi-ExternalRoot-Helper
        #depth: 1
        #version: master
      #tags: git
