---
- name: Configure Workstations
  hosts: workstations
  tags: workstations
  roles:
    - { role: ack,         tags: ack }
    - { role: ag,          tags: ag }
    - { role: bash,        tags: bash }
    - { role: curl,        tags: curl }
    - { role: wget,        tags: wget }
    - { role: ssh,         tags: ssh }
    - { role: gpg,         tags: gpg }
    - { role: git,         tags: git }
    - { role: gist,        tags: gist }
    - { role: ghi,         tags: ghi }
    - { role: hub,         tags: hub }
    - { role: keybase,     tags: keybase }
    - { role: vim,         tags: vim }
    - { role: tmux,        tags: tmux }
    - { role: rackspace,   tags: rackspace }
    - { role: weechat,     tags: weechat }
    - { role: ruby,        tags: ruby, ruby_versions: ['1.9.3-p551', '2.1.8', '2.2.4', '2.3.0'], ruby_default_version: '1.9.3-p551', ruby_default_gems: ['rubygems-update', 'bundler', 'pry'] }
    - { role: python,      tags: python, python_versions: ['2.7.11', '3.4.4', '3.5.1'], python_default_version: '2.7.11', python_default_packages: ['pip', 'wheel', 'flake8'] }
    - { role: perl,        tags: perl, perl_versions: ['5.20.3', '5.22.1'], perl_default_version: '5.20.3', perl_default_modules: ['Carton', 'Perl::Tidy'] }
    - { role: alfred,      tags: alfred }
    - { role: boom,        tags: boom }
    - { role: caffeine,    tags: caffeine }
    - { role: cloak,       tags: cloak }
    - { role: chrome,      tags: chrome }
    - { role: dropbox,     tags: dropbox }
    - { role: evernote,    tags: evernote }
    - { role: flux,        tags: flux }
    - { role: iterm2,      tags: iterm2 }
    - { role: onepassword, tags: onepassword }
    - { role: macvim,      tags: macvim }
    - { role: omnifocus,   tags: omnifocus }
    - { role: slack,       tags: slack }
    - { role: sizeup,      tags: sizeup }
    - { role: steam,       tags: steam }
    - { role: terminal,    tags: terminal }
    - { role: tunnelblick, tags: tunnelblick }
    - { role: vagrant,     tags: vagrant }
    - { role: virtualbox,  tags: virtualbox }
    - { role: p4merge,     tags: p4merge, when: ansible_distribution == 'MacOSX' }
