---
galaxy_info:
  author: Christopher H. Laco
  description: Install and configure Vim
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - development
    - system
dependencies:
  - { role: ack }
  - { role: ag }
  - { role: aspell }
  - { role: build-essential }
  - { role: homebrew, when: ansible_pkg_mgr == 'homebrew' }
  - { role: git }
