---
perl_tidyrc_file: '{{ ansible_env.HOME }}/.perltidyrc'
perl_install_command: '{{ plenv_binary }} install'
perl_versions_directory: '{{ plenv_versions_directory }}'
perl_versions:
  - 5.18.2
  - 5.18.4
  - 5.20.3
  - 5.22.3
  - 5.24.1
perl_default_version: system
perl_default_modules:
  - Carton
  - Perl::Tidy
perl_required_packages:
  macosx:
    - libyaml
    - openssl
    - readline
    - sqlite
  fedora:
    - openssl-devel
    - libyaml-devel
    - readline-devel
    - sqlite
    - sqlite-devel
  ubuntu:
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - sqlite3
    - libsqlite3-dev
