---
- name: Install Required Packages | Homebrew
  homebrew_cask: name=alfred state=present
  when: ansible_distribution == 'MacOSX'


- name: Create Alfred License Folder
  file: name={{ alfred_license_folder }} state=directory

- name: Install Alfred License
  template: src=license.plist.j2 dest={{ alfred_license_file }}

- name: Add Alfred to Dock
  shell: dockutil --find 'Alfred' || dockutil --add '~/Applications/Alfred 2.app'
  changed_when: False
  when: ansible_distribution == 'MacOSX'
