---
- name: Add System76 Repository
  apt_repository:
    repo: '{{ system76_repository_url.ubuntu[system76_theme | lower] }}'
    state: latest
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install Required Packages | Packages
  package:
    name: '{{ item }}'
    state: latest
  become: yes
  with_items: '{{ system76_required_packages.ubuntu[system76_theme | lower] | default([]) }}'
  when: ansible_distribution == 'Ubuntu'
