---
galaxy_info:
  author: Christopher H. Laco
  description: Install and configure Ruby
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - development
    - system
dependencies:
  - { role: rbenv, tags: rbenv, rbenv_default_gems: '{{ ruby_default_gems }}' }
