---
- name: Install Required Packages | Homebrew
  package: name={{ item }} state=latest
  with_items: '{{ python_required_packages[ansible_distribution | lower] | default([]) }}'
  when: ansible_distribution == 'MacOSX'

- name: Install Required Packages | Packages
  package: name={{ item }} state=latest
  become: yes
  with_items: '{{ python_required_packages[ansible_distribution | lower] | default([]) }}'
  when: ansible_distribution != 'MacOSX'

- name: Create Pip Directory
  file: path={{ python_pip_config_directory }} state=directory
  tags: python-pip-config

- name: Configure Pip
  template: src=pip.conf.j2 dest={{ python_pip_config_file}}
  tags: python-pip-config

- name: Install Python Versions
  shell: "{{ python_install_command }} {{ item }}"
  args:
    creates: "{{ python_versions_directory }}/{{ item }}"
  with_items: '{{ python_versions }}'
  tags: python-install
  notify: rehash pyenv

- name: Configure Default Version
  template: src=version.j2 dest={{ pyenv_root_directory }}/version
  when: python_default_version is defined
  tags: python-install, python-default-version
  notify: rehash pyenv

- name: Install Default Packages | Ansible
  pip: name={{ item[1] }} executable={{ pyenv_versions_directory }}/{{ item[0] }}/bin/pip state=latest
  with_nested:
    - '{{ python_versions }}'
    - '{{ python_default_packages }}'
  tags: python-install, python-default-packages
  notify: rehash pyenv

- name: Load Installed Versions
  shell: "{{ pyenv_binary }} versions --bare"
  register: pyenv_installed_versions
  changed_when: False
  tags: python-cleanup

- name: Remove Older Versions
  shell: "{{ pyenv_binary }} uninstall --force {{ item }}"
  args:
    removes: "{{ python_versions_directory }}/{{ item }}"
  when: item not in python_versions
  with_items: "{{ pyenv_installed_versions.stdout_lines }}"
  tags: python-cleanup
  notify: rehash pyenv
