---
galaxy_info:
  author: Christopher H. Laco
  description: Configure Dock
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
dependencies: []
