---
- name: Install Required Packages | Homebrew
  homebrew_cask: name=slack state=present
  when: ansible_distribution == 'MacOSX'

- name: Add Slack to Dock
  shell: dockutil --add '/Applications/Slack.app' --label 'Slack' --replacing 'Slack'
  changed_when: False
  when: ansible_distribution == 'MacOSX'
