galaxy_info:
  author: Christopher H. Laco
  description: Move Root File System on RaspberryPi
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Debian
      versions:
        - jessie
  categories:
    - system
dependencies:
