---
- name: Configure Internal Trackpad
  osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
    state: present
    dict_add: True
  with_items: '{{ trackpad_defaults.macosx }}'
  when: ansible_distribution == 'MacOSX'
  tags: trackpad-config

- name: Configure Bluetooth Trackpad
  osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
    state: present
    dict_add: True
  with_items: '{{ trackpad_defaults.macosx }}'
  when: ansible_distribution == 'MacOSX'
  tags: trackpad-config

- name: Configure Global Tap Behavior
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    type: int
    value: 1
  when: ansible_distribution == 'MacOSX'
  tags: trackpad-config

- name: Configure Global Behavior
  osx_defaults:
    host: currentHost
    domain: NSGlobalDomain
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
  with_items: '{{ trackpad_host_defaults.macosx }}'
  when: ansible_distribution == 'MacOSX'
  tags: trackpad-config
