---
- name: Configure Internal Trackpad
  osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
    state: present
    dict_add: True
  with_items: '{{ trackpad_defaults.macosx }}'
  when: ansible_distribution == 'MacOSX'
  tags: trackpad-config

- name: Configure Internal Trackpad
  osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
    state: present
    dict_add: True
  with_items: '{{ trackpad_defaults.macosx }}'
  when: ansible_distribution == 'MacOSX'
  tags: trackpad-config
