---
- name: Install Required Packages | Homebrew
  homebrew_cask: name=virtualbox state=present
  when: ansible_distribution == 'MacOSX'

- name: Add VirtualBox to Dock
  shell: dockutil --add '/Applications/VirtualBox.app' --label 'VirtualBox' --replacing 'VirtualBox'
  changed_when: False
  when: ansible_distribution == 'MacOSX'
