---
- name: Install Required Packages | Homebrew
  homebrew_cask: name=evernote state=present
  when: ansible_distribution == 'MacOSX'

- name: Add Evernote to Dock
  shell: dockutil --add '/Applications/Evernote.app' --label 'Evernote' --replacing 'Evernote'
  changed_when: False
  when: ansible_distribution == 'MacOSX'
