---
- name: Install Required Packages | Homebrew
  homebrew_cask: name=evernote state=present
  when: ansible_distribution == 'MacOSX'

- name: Add Evernote to Dock
  shell: dockutil --find 'Evernote' || dockutil --add '/Applications/Evernote.app'
  changed_when: False
  when: ansible_distribution == 'MacOSX'
