---
galaxy_info:
  author: Christopher H. Laco
  description: Install and configure RbEnv
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Darwin
      versions:
        - 10.11
    - name: Debian
      versions:
        - wheezy
        - jessie
    - name: Fedora
      versions:
        - 23
    - name: Ubuntu
      versions:
        - trusty
  categories:
    - development
    - system
dependencies:
  - build-essential
  - bash
  - git
