---
- name: Install Required Packages | Homebrew
  package: name=dockutil state=latest
  when: ansible_distribution == 'MacOSX'

- name: Add Downloads Folder
  shell: dockutil --add '~/Downloads' --view list --display folder --section others --label 'Downloads' --replacing 'Downloads'
  changed_when: False
