---
- name: Install Required Packages | Homebrew
  homebrew_cask: name=dropbox state=present
  when: ansible_distribution == 'MacOSX'

- name: Add Dropbox to Dock
  shell: dockutil --find 'Dropbox' || dockutil --add '/Applications/Dropbox.app'
  changed_when: False
  when: ansible_distribution == 'MacOSX'
