---
galaxy_info:
  author: Christopher H. Laco
  description: Configure and update Ansible
  license: MIT
  min_ansible_version: 2.5
  platforms:
    - name: Darwin
      versions:
        - all
    - name: Ubuntu
      versions:
        - bionic
  categories:
    - development
    - system
dependencies:
  - { role: homebrew, when: ansible_pkg_mgr == "homebrew" }
