---
galaxy_info:
  author: Christopher H. Laco
  description: Configure and update Ansible
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - development
    - system
dependencies:
  - { role: homebrew, when: ansible_pkg_mgr == 'homebrew' }
