---
- name: Install Required Packages | Homebrew
  homebrew_cask: name=boom state=present
  when: ansible_distribution == 'MacOSX'

- name: Add Boom to Dock
  shell: dockutil --find 'Boom' || dockutil --add '~/Applications/Boom 2.app'
  changed_when: False
  when: ansible_distribution == 'MacOSX'
