---
galaxy_info:
  author: Christopher H. Laco
  description: Install and configure iTerm2
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - development
    - system
dependencies:
  - { role: dockutil, when: ansible_pkg_mgr == 'homebrew' }
  - { role: homebrew, when: ansible_pkg_mgr == 'homebrew' }
  - { role: fonts }
  - { role: solarized }
  - { role: tmux }
