---
- name: Install Required Packages | Homebrew
  homebrew_cask: name={{ item }} state=present
  with_items: '{{ plex_required_packages[ansible_distribution | lower] | default([]) }}'
  when: ansible_distribution == 'MacOSX'

- name: Install Required Packages | Packages
  package: name={{ item }} state=latest
  become: yes
  with_items: '{{ plex_required_packages[ansible_distribution | lower] | default([]) }}'
  when: ansible_distribution != 'MacOSX'

- name: Add Plex to Dock
  shell: dockutil --find 'Plex Media Player' || dockutil --add '/Applications/Plex Media Player.app'
  changed_when: False
  when: ansible_distribution == 'MacOSX'
