---
- name: Install Required Packages | Homebrew
  package: name=aspell install_options='--with-lang-en' state=latest
  when: ansible_distribution == 'MacOSX'

- name: Install Required Packages | Packages
  package: name={{ item }} state=latest
  become: yes
  with_items: '{{ aspell_required_packages[ansible_distribution | lower] | default([]) }}'
  when: ansible_distribution != 'MacOSX'
