---
- name: Install Required Packages | Homebrew
  homebrew_cask: name=tunnelblick state=present
  when: ansible_distribution == 'MacOSX'

- name: Add Tunnelblick to Dock
  shell: dockutil --add '/Applications/Tunnelblick.app' --label 'Tunnelblick' --replacing 'Tunnelblick'
  changed_when: False
  when: ansible_distribution == 'MacOSX'
